/*

 DEBUGTILES_U.H

 Include File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 8

  Palette colors       : Included.
  SGB Palette          : None.
  CGB Palette          : None.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/

#ifndef __debugTiles_u_h_INCLUDE
#define __debugTiles_u_h_INCLUDE

/* Bank of tiles. */
#define debugTiles_uBank 0

/* Super Gameboy palette 0 */
#define debugTiles_uSGBPal0c0 6076
#define debugTiles_uSGBPal0c1 8935
#define debugTiles_uSGBPal0c2 6596
#define debugTiles_uSGBPal0c3 5344

/* Super Gameboy palette 1 */
#define debugTiles_uSGBPal1c0 6076
#define debugTiles_uSGBPal1c1 8935
#define debugTiles_uSGBPal1c2 6596
#define debugTiles_uSGBPal1c3 5344

/* Super Gameboy palette 2 */
#define debugTiles_uSGBPal2c0 6076
#define debugTiles_uSGBPal2c1 8935
#define debugTiles_uSGBPal2c2 6596
#define debugTiles_uSGBPal2c3 5344

/* Super Gameboy palette 3 */
#define debugTiles_uSGBPal3c0 6076
#define debugTiles_uSGBPal3c1 8935
#define debugTiles_uSGBPal3c2 6596
#define debugTiles_uSGBPal3c3 5344

/* Gameboy Color palette 0 */
#define debugTiles_uCGBPal0c0 6076
#define debugTiles_uCGBPal0c1 8935
#define debugTiles_uCGBPal0c2 6596
#define debugTiles_uCGBPal0c3 5344

/* Gameboy Color palette 1 */
#define debugTiles_uCGBPal1c0 6076
#define debugTiles_uCGBPal1c1 8935
#define debugTiles_uCGBPal1c2 6596
#define debugTiles_uCGBPal1c3 5344

/* Gameboy Color palette 2 */
#define debugTiles_uCGBPal2c0 6076
#define debugTiles_uCGBPal2c1 8935
#define debugTiles_uCGBPal2c2 6596
#define debugTiles_uCGBPal2c3 5344

/* Gameboy Color palette 3 */
#define debugTiles_uCGBPal3c0 6076
#define debugTiles_uCGBPal3c1 8935
#define debugTiles_uCGBPal3c2 6596
#define debugTiles_uCGBPal3c3 5344

/* Gameboy Color palette 4 */
#define debugTiles_uCGBPal4c0 6076
#define debugTiles_uCGBPal4c1 8935
#define debugTiles_uCGBPal4c2 6596
#define debugTiles_uCGBPal4c3 5344

/* Gameboy Color palette 5 */
#define debugTiles_uCGBPal5c0 6076
#define debugTiles_uCGBPal5c1 8935
#define debugTiles_uCGBPal5c2 6596
#define debugTiles_uCGBPal5c3 5344

/* Gameboy Color palette 6 */
#define debugTiles_uCGBPal6c0 6076
#define debugTiles_uCGBPal6c1 8935
#define debugTiles_uCGBPal6c2 6596
#define debugTiles_uCGBPal6c3 5344

/* Gameboy Color palette 7 */
#define debugTiles_uCGBPal7c0 6076
#define debugTiles_uCGBPal7c1 8935
#define debugTiles_uCGBPal7c2 6596
#define debugTiles_uCGBPal7c3 5344
/* Start of tile array. */
extern const unsigned char debugTiles_u[];

#endif

/* End of DEBUGTILES_U.H */
