/*

 DEBUGTILES.H

 Include File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : GB-Compress.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 8

  Palette colors       : Included.
  SGB Palette          : None.
  CGB Palette          : None.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/

#ifndef __debugTiles_h_INCLUDE
#define __debugTiles_h_INCLUDE

/* Bank of tiles. */
#define debugTilesBank 0

/* Super Gameboy palette 0 */
#define debugTilesSGBPal0c0 6076
#define debugTilesSGBPal0c1 8935
#define debugTilesSGBPal0c2 6596
#define debugTilesSGBPal0c3 5344

/* Super Gameboy palette 1 */
#define debugTilesSGBPal1c0 6076
#define debugTilesSGBPal1c1 8935
#define debugTilesSGBPal1c2 6596
#define debugTilesSGBPal1c3 5344

/* Super Gameboy palette 2 */
#define debugTilesSGBPal2c0 6076
#define debugTilesSGBPal2c1 8935
#define debugTilesSGBPal2c2 6596
#define debugTilesSGBPal2c3 5344

/* Super Gameboy palette 3 */
#define debugTilesSGBPal3c0 6076
#define debugTilesSGBPal3c1 8935
#define debugTilesSGBPal3c2 6596
#define debugTilesSGBPal3c3 5344

/* Gameboy Color palette 0 */
#define debugTilesCGBPal0c0 6076
#define debugTilesCGBPal0c1 8935
#define debugTilesCGBPal0c2 6596
#define debugTilesCGBPal0c3 5344

/* Gameboy Color palette 1 */
#define debugTilesCGBPal1c0 6076
#define debugTilesCGBPal1c1 8935
#define debugTilesCGBPal1c2 6596
#define debugTilesCGBPal1c3 5344

/* Gameboy Color palette 2 */
#define debugTilesCGBPal2c0 6076
#define debugTilesCGBPal2c1 8935
#define debugTilesCGBPal2c2 6596
#define debugTilesCGBPal2c3 5344

/* Gameboy Color palette 3 */
#define debugTilesCGBPal3c0 6076
#define debugTilesCGBPal3c1 8935
#define debugTilesCGBPal3c2 6596
#define debugTilesCGBPal3c3 5344

/* Gameboy Color palette 4 */
#define debugTilesCGBPal4c0 6076
#define debugTilesCGBPal4c1 8935
#define debugTilesCGBPal4c2 6596
#define debugTilesCGBPal4c3 5344

/* Gameboy Color palette 5 */
#define debugTilesCGBPal5c0 6076
#define debugTilesCGBPal5c1 8935
#define debugTilesCGBPal5c2 6596
#define debugTilesCGBPal5c3 5344

/* Gameboy Color palette 6 */
#define debugTilesCGBPal6c0 6076
#define debugTilesCGBPal6c1 8935
#define debugTilesCGBPal6c2 6596
#define debugTilesCGBPal6c3 5344

/* Gameboy Color palette 7 */
#define debugTilesCGBPal7c0 6076
#define debugTilesCGBPal7c1 8935
#define debugTilesCGBPal7c2 6596
#define debugTilesCGBPal7c3 5344
/* Start of tile array. */
extern const unsigned char debugTiles[];

#endif

/* End of DEBUGTILES.H */
