/*

 DEBUGMAP.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 255
   Map size      : 32 x 16
   Tile set      : dungeon_32x32.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Planes are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/
#ifndef __debugMap_h_INCLUDE
#define __debugMap_h_INCLUDE

#define debugMapWidth 32
#define debugMapHeight 16
#define debugMapBank 255

#define debugMap debugMapPLN0
extern const void __bank_debugMapPLN0;
extern const unsigned char debugMapPLN0[];

#endif

/* End of DEBUGMAP.H */
