/*

 HEROTILES.H

 Include File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : GB-Compress.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 1 to 64

  Palette colors       : Included.
  SGB Palette          : None.
  CGB Palette          : None.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/

#ifndef __heroTiles_h_INCLUDE
#define __heroTiles_h_INCLUDE

/* Bank of tiles. */
#define heroTilesBank 0

/* Super Gameboy palette 0 */
#define heroTilesSGBPal0c0 0
#define heroTilesSGBPal0c1 0
#define heroTilesSGBPal0c2 0
#define heroTilesSGBPal0c3 0

/* Super Gameboy palette 1 */
#define heroTilesSGBPal1c0 6076
#define heroTilesSGBPal1c1 8935
#define heroTilesSGBPal1c2 6596
#define heroTilesSGBPal1c3 5344

/* Super Gameboy palette 2 */
#define heroTilesSGBPal2c0 6076
#define heroTilesSGBPal2c1 8935
#define heroTilesSGBPal2c2 6596
#define heroTilesSGBPal2c3 5344

/* Super Gameboy palette 3 */
#define heroTilesSGBPal3c0 6076
#define heroTilesSGBPal3c1 8935
#define heroTilesSGBPal3c2 6596
#define heroTilesSGBPal3c3 5344

/* Gameboy Color palette 0 */
#define heroTilesCGBPal0c0 21304
#define heroTilesCGBPal0c1 13905
#define heroTilesCGBPal0c2 7497
#define heroTilesCGBPal0c3 2147

/* Gameboy Color palette 1 */
#define heroTilesCGBPal1c0 6076
#define heroTilesCGBPal1c1 8935
#define heroTilesCGBPal1c2 6596
#define heroTilesCGBPal1c3 5344

/* Gameboy Color palette 2 */
#define heroTilesCGBPal2c0 6076
#define heroTilesCGBPal2c1 8935
#define heroTilesCGBPal2c2 6596
#define heroTilesCGBPal2c3 5344

/* Gameboy Color palette 3 */
#define heroTilesCGBPal3c0 6076
#define heroTilesCGBPal3c1 8935
#define heroTilesCGBPal3c2 6596
#define heroTilesCGBPal3c3 5344

/* Gameboy Color palette 4 */
#define heroTilesCGBPal4c0 6076
#define heroTilesCGBPal4c1 8935
#define heroTilesCGBPal4c2 6596
#define heroTilesCGBPal4c3 5344

/* Gameboy Color palette 5 */
#define heroTilesCGBPal5c0 6076
#define heroTilesCGBPal5c1 8935
#define heroTilesCGBPal5c2 6596
#define heroTilesCGBPal5c3 5344

/* Gameboy Color palette 6 */
#define heroTilesCGBPal6c0 6076
#define heroTilesCGBPal6c1 8935
#define heroTilesCGBPal6c2 6596
#define heroTilesCGBPal6c3 5344

/* Gameboy Color palette 7 */
#define heroTilesCGBPal7c0 6076
#define heroTilesCGBPal7c1 8935
#define heroTilesCGBPal7c2 6596
#define heroTilesCGBPal7c3 5344
/* Start of tile array. */
extern const unsigned char heroTiles[];

#endif

/* End of HEROTILES.H */
