//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_heroTiles_gg_H
#define METASPRITE_heroTiles_gg_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define heroTiles_gg_TILE_ORIGIN 0
#define heroTiles_gg_TILE_W 8
#define heroTiles_gg_TILE_H 8
#define heroTiles_gg_WIDTH 336
#define heroTiles_gg_HEIGHT 32
#define heroTiles_gg_TILE_COUNT 81
#define heroTiles_gg_PALETTE_COUNT 1
#define heroTiles_gg_COLORS_PER_PALETTE 16
#define heroTiles_gg_TOTAL_COLORS 16

BANKREF_EXTERN(heroTiles_gg)

extern const palette_color_t heroTiles_gg_palettes[16];
extern const uint8_t heroTiles_gg_tiles[2592];

#endif
