//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_levelHero_tiles_gg_H
#define METASPRITE_levelHero_tiles_gg_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define levelHero_tiles_gg_TILE_ORIGIN 0
#define levelHero_tiles_gg_TILE_W 8
#define levelHero_tiles_gg_TILE_H 8
#define levelHero_tiles_gg_WIDTH 160
#define levelHero_tiles_gg_HEIGHT 112
#define levelHero_tiles_gg_TILE_COUNT 66
#define levelHero_tiles_gg_PALETTE_COUNT 1
#define levelHero_tiles_gg_COLORS_PER_PALETTE 16
#define levelHero_tiles_gg_TOTAL_COLORS 16
#define levelHero_tiles_gg_MAP_ATTRIBUTES 0
extern const unsigned char levelHero_tiles_gg_map[280];
#define levelHero_tiles_gg_map_attributes levelHero_tiles_gg_map

BANKREF_EXTERN(levelHero_tiles_gg)

extern const palette_color_t levelHero_tiles_gg_palettes[16];
extern const uint8_t levelHero_tiles_gg_tiles[2112];

#endif
