/*

 LEVELHERO_TILES.H

 Include File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : GB-Compress.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 79

  Palette colors       : Included.
  SGB Palette          : None.
  CGB Palette          : None.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/

#ifndef __levelHero_tiles_h_INCLUDE
#define __levelHero_tiles_h_INCLUDE

/* Bank of tiles. */
#define levelHero_tilesBank 0

/* Super Gameboy palette 0 */
#define levelHero_tilesSGBPal0c0 0
#define levelHero_tilesSGBPal0c1 0
#define levelHero_tilesSGBPal0c2 0
#define levelHero_tilesSGBPal0c3 0

/* Super Gameboy palette 1 */
#define levelHero_tilesSGBPal1c0 6076
#define levelHero_tilesSGBPal1c1 8935
#define levelHero_tilesSGBPal1c2 6596
#define levelHero_tilesSGBPal1c3 5344

/* Super Gameboy palette 2 */
#define levelHero_tilesSGBPal2c0 6076
#define levelHero_tilesSGBPal2c1 8935
#define levelHero_tilesSGBPal2c2 6596
#define levelHero_tilesSGBPal2c3 5344

/* Super Gameboy palette 3 */
#define levelHero_tilesSGBPal3c0 6076
#define levelHero_tilesSGBPal3c1 8935
#define levelHero_tilesSGBPal3c2 6596
#define levelHero_tilesSGBPal3c3 5344

/* Gameboy Color palette 0 */
#define levelHero_tilesCGBPal0c0 21304
#define levelHero_tilesCGBPal0c1 13905
#define levelHero_tilesCGBPal0c2 7497
#define levelHero_tilesCGBPal0c3 2147

/* Gameboy Color palette 1 */
#define levelHero_tilesCGBPal1c0 6076
#define levelHero_tilesCGBPal1c1 8935
#define levelHero_tilesCGBPal1c2 6596
#define levelHero_tilesCGBPal1c3 5344

/* Gameboy Color palette 2 */
#define levelHero_tilesCGBPal2c0 6076
#define levelHero_tilesCGBPal2c1 8935
#define levelHero_tilesCGBPal2c2 6596
#define levelHero_tilesCGBPal2c3 5344

/* Gameboy Color palette 3 */
#define levelHero_tilesCGBPal3c0 6076
#define levelHero_tilesCGBPal3c1 8935
#define levelHero_tilesCGBPal3c2 6596
#define levelHero_tilesCGBPal3c3 5344

/* Gameboy Color palette 4 */
#define levelHero_tilesCGBPal4c0 6076
#define levelHero_tilesCGBPal4c1 8935
#define levelHero_tilesCGBPal4c2 6596
#define levelHero_tilesCGBPal4c3 5344

/* Gameboy Color palette 5 */
#define levelHero_tilesCGBPal5c0 6076
#define levelHero_tilesCGBPal5c1 8935
#define levelHero_tilesCGBPal5c2 6596
#define levelHero_tilesCGBPal5c3 5344

/* Gameboy Color palette 6 */
#define levelHero_tilesCGBPal6c0 6076
#define levelHero_tilesCGBPal6c1 8935
#define levelHero_tilesCGBPal6c2 6596
#define levelHero_tilesCGBPal6c3 5344

/* Gameboy Color palette 7 */
#define levelHero_tilesCGBPal7c0 6076
#define levelHero_tilesCGBPal7c1 8935
#define levelHero_tilesCGBPal7c2 6596
#define levelHero_tilesCGBPal7c3 5344
/* Start of tile array. */
extern const unsigned char levelHero_tiles[];

#endif

/* End of LEVELHERO_TILES.H */
