/*

 HEROTILES-GB.H

 Include File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : GB-Compress.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 66

  Palette colors       : Included.
  SGB Palette          : None.
  CGB Palette          : None.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/

#ifndef __heroTiles_gb_h_INCLUDE
#define __heroTiles_gb_h_INCLUDE

/* Bank of tiles. */
#define heroTiles_tilesBank 0

/* Super Gameboy palette 0 */
#define heroTiles_tilesSGBPal0c0 21304
#define heroTiles_tilesSGBPal0c1 32767
#define heroTiles_tilesSGBPal0c2 2399
#define heroTiles_tilesSGBPal0c3 0

/* Super Gameboy palette 1 */
#define heroTiles_tilesSGBPal1c0 21304
#define heroTiles_tilesSGBPal1c1 8935
#define heroTiles_tilesSGBPal1c2 6596
#define heroTiles_tilesSGBPal1c3 5344

/* Super Gameboy palette 2 */
#define heroTiles_tilesSGBPal2c0 21304
#define heroTiles_tilesSGBPal2c1 8935
#define heroTiles_tilesSGBPal2c2 6596
#define heroTiles_tilesSGBPal2c3 5344

/* Super Gameboy palette 3 */
#define heroTiles_tilesSGBPal3c0 21304
#define heroTiles_tilesSGBPal3c1 8935
#define heroTiles_tilesSGBPal3c2 6596
#define heroTiles_tilesSGBPal3c3 5344

/* Gameboy Color palette 0 */
#define heroTiles_tilesCGBPal0c0 21304
#define heroTiles_tilesCGBPal0c1 13905
#define heroTiles_tilesCGBPal0c2 7497
#define heroTiles_tilesCGBPal0c3 2147

/* Gameboy Color palette 1 */
#define heroTiles_tilesCGBPal1c0 6076
#define heroTiles_tilesCGBPal1c1 8935
#define heroTiles_tilesCGBPal1c2 6596
#define heroTiles_tilesCGBPal1c3 5344

/* Gameboy Color palette 2 */
#define heroTiles_tilesCGBPal2c0 6076
#define heroTiles_tilesCGBPal2c1 8935
#define heroTiles_tilesCGBPal2c2 6596
#define heroTiles_tilesCGBPal2c3 5344

/* Gameboy Color palette 3 */
#define heroTiles_tilesCGBPal3c0 6076
#define heroTiles_tilesCGBPal3c1 8935
#define heroTiles_tilesCGBPal3c2 6596
#define heroTiles_tilesCGBPal3c3 5344

/* Gameboy Color palette 4 */
#define heroTiles_tilesCGBPal4c0 6076
#define heroTiles_tilesCGBPal4c1 8935
#define heroTiles_tilesCGBPal4c2 6596
#define heroTiles_tilesCGBPal4c3 5344

/* Gameboy Color palette 5 */
#define heroTiles_tilesCGBPal5c0 6076
#define heroTiles_tilesCGBPal5c1 8935
#define heroTiles_tilesCGBPal5c2 6596
#define heroTiles_tilesCGBPal5c3 5344

/* Gameboy Color palette 6 */
#define heroTiles_tilesCGBPal6c0 6076
#define heroTiles_tilesCGBPal6c1 8935
#define heroTiles_tilesCGBPal6c2 6596
#define heroTiles_tilesCGBPal6c3 5344

/* Gameboy Color palette 7 */
#define heroTiles_tilesCGBPal7c0 6076
#define heroTiles_tilesCGBPal7c1 8935
#define heroTiles_tilesCGBPal7c2 6596
#define heroTiles_tilesCGBPal7c3 5344
/* Start of tile array. */
extern const unsigned char heroTiles_tiles[];

#endif

/* End of HEROTILES-GB.H */
