/*

 LEVELHERO_MAP-GB.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 20 x 14
   Tile set      : levelHero.gbm.tiles.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Planes are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/
#ifndef __levelHero_map_gb_h_INCLUDE
#define __levelHero_map_gb_h_INCLUDE

#define levelHero_mapWidth 20
#define levelHero_mapHeight 14
#define levelHero_mapBank 0

#define levelHero_map levelHero_mapPLN0
extern const unsigned char levelHero_mapPLN0[];

#endif

/* End of LEVELHERO_MAP-GB.H */
