/*

 MAINMENU_MAP.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 20 x 18
   Tile set      : mainMenu.gbm.tiles.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Planes are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/
#ifndef __mainMenu_map_h_INCLUDE
#define __mainMenu_map_h_INCLUDE

#define mainMenu_mapWidth 20
#define mainMenu_mapHeight 18
#define mainMenu_mapBank 0

#define mainMenu_map mainMenu_mapPLN0
extern const unsigned char mainMenu_mapPLN0[];

#endif

/* End of MAINMENU_MAP.H */
