//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_sgb_border_H
#define METASPRITE_sgb_border_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define sgb_border_TILE_ORIGIN 0
#define sgb_border_TILE_W 8
#define sgb_border_TILE_H 8
#define sgb_border_WIDTH 256
#define sgb_border_HEIGHT 224
#define sgb_border_TILE_COUNT 107
#define sgb_border_PALETTE_COUNT 1
#define sgb_border_COLORS_PER_PALETTE 16
#define sgb_border_TOTAL_COLORS 16
#define sgb_border_MAP_ATTRIBUTES 0
#define sgb_border_MAP_ATTRIBUTES_WIDTH 32
#define sgb_border_MAP_ATTRIBUTES_HEIGHT 28
#define sgb_border_MAP_ATTRIBUTES_PACKED_WIDTH 32
#define sgb_border_MAP_ATTRIBUTES_PACKED_HEIGHT 28
extern const unsigned char sgb_border_map[1792];
#define sgb_border_map_attributes sgb_border_map

BANKREF_EXTERN(sgb_border)

extern const palette_color_t sgb_border_palettes[16];
extern const uint8_t sgb_border_tiles[3424];

#endif
