/*

 WINDOWTILES.H

 Include File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : GB-Compress.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 100 to 126

  Palette colors       : None.
  SGB Palette          : None.
  CGB Palette          : None.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/

#ifndef __windowTiles_h_INCLUDE
#define __windowTiles_h_INCLUDE

/* Bank of tiles. */
#define windowTilesBank 0
/* Start of tile array. */
extern const unsigned char windowTiles[];

#endif

/* End of WINDOWTILES.H */
