//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_bossDbg_Tiles_gg_H
#define METASPRITE_bossDbg_Tiles_gg_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define bossDbg_Tiles_gg_TILE_ORIGIN 0
#define bossDbg_Tiles_gg_TILE_W 8
#define bossDbg_Tiles_gg_TILE_H 8
#define bossDbg_Tiles_gg_WIDTH 8
#define bossDbg_Tiles_gg_HEIGHT 48
#define bossDbg_Tiles_gg_TILE_COUNT 6
#define bossDbg_Tiles_gg_PALETTE_COUNT 1
#define bossDbg_Tiles_gg_COLORS_PER_PALETTE 16
#define bossDbg_Tiles_gg_TOTAL_COLORS 16

BANKREF_EXTERN(bossDbg_Tiles_gg)

extern const palette_color_t bossDbg_Tiles_gg_palettes[16];
extern const uint8_t bossDbg_Tiles_gg_tiles[192];

#endif
