//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_heroTiles_gg_left_H
#define METASPRITE_heroTiles_gg_left_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define heroTiles_gg_left_TILE_ORIGIN 0
#define heroTiles_gg_left_TILE_W 8
#define heroTiles_gg_left_TILE_H 8
#define heroTiles_gg_left_WIDTH 536
#define heroTiles_gg_left_HEIGHT 8
#define heroTiles_gg_left_TILE_COUNT 67
#define heroTiles_gg_left_PALETTE_COUNT 1
#define heroTiles_gg_left_COLORS_PER_PALETTE 16
#define heroTiles_gg_left_TOTAL_COLORS 16

BANKREF_EXTERN(heroTiles_gg_left)

extern const palette_color_t heroTiles_gg_left_palettes[16];
extern const uint8_t heroTiles_gg_left_tiles[2144];

#endif
