//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_win_tiles_gg_H
#define METASPRITE_win_tiles_gg_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define win_tiles_gg_TILE_ORIGIN 100
#define win_tiles_gg_TILE_W 8
#define win_tiles_gg_TILE_H 8
#define win_tiles_gg_WIDTH 144
#define win_tiles_gg_HEIGHT 8
#define win_tiles_gg_TILE_COUNT 18
#define win_tiles_gg_PALETTE_COUNT 1
#define win_tiles_gg_COLORS_PER_PALETTE 16
#define win_tiles_gg_TOTAL_COLORS 16
#define win_tiles_gg_MAP_ATTRIBUTES 0
extern const unsigned char win_tiles_gg_map[18];
#define win_tiles_gg_map_attributes win_tiles_gg_map

BANKREF_EXTERN(win_tiles_gg)

extern const palette_color_t win_tiles_gg_palettes[16];
extern const uint8_t win_tiles_gg_tiles[576];

#endif
